DROP TABLE IF EXISTS payment;
create table payment
(
	id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	amount          DECIMAL NOT NULL,
	bic             VARCHAR(255),
	cancellation_date   TIMESTAMP,
	cancellation_fee    DECIMAL,
	creation_date       TIMESTAMP default CURRENT_TIMESTAMP NOT NULL,
	creditor_iban       VARCHAR(255) NOT NULL,
	currency        VARCHAR(3) NOT NULL,
	debtor_iban     VARCHAR(255) NOT NULL,
	details         VARCHAR(255),
	notified        BOOLEAN NOT NULL
);



